### ISSUE TITLE
Support 4chan captcha

### ISSUE THREAD

**Issue by ewmb7701** [PietroCarrara/Clover#3]
The current version of Clover does not support 4chan's new captcha: https://github.com/chandevel/Clover/issues/801

A currently-maintained fork was made to support this new captcha: https://github.com/nnuudev/BlueClover. 

Obviously the incidence of 4chan crossposters is low, but this would remove the need for two apps.

**Comment by PietroCarrara** [comment]
Even though this repo is named Clover, it's actually a [kuroba](https://github.com/Adamantcheese/Kuroba) fork. From what I can see, Kuroba is yet to implement the new captcha.
